String englishTerms =
    """<strong>The Purpose of the Terms and Conditions</strong>\n
    <p>We welcome you as a user of “Harkat” smart electronic services, and we invite you to read these terms and conditions carefully. Our aim is to define the principles and obligations necessary for the use of the smart electronic services available on the electronic platform “Harkat” by stating the user’s obligations and terms of use.
Definitions and Expressions in the Terms and Conditions
Each of the following expressions shall has the meaning next to each for the purpose of this Agreement:
Smart Electronic Services: All the smart electronic services provided by the “Harkat” Company to the subscribing users or other users in any form of smart electronic services, for example: registration of subscription, advertisements, requesting services of all kinds. Moreover, the secure electronic payments are done through the smart platform on the Company’s application and website.
User: Everyone who has access to all the contents and materials available on the Company’s official website on smart applications and on all platforms, or dealing with the same in any form, through the use of the user’s service account (registered username and password). The user may be a subscriber or a non-subscriber.
Contents: All the contents of the service in terms of software and databases, as well as data files, written texts, maps or prices, or other photographed or written materials contained therein.
I have read, understood and accepted all existing, updated or amended terms and conditions
By entering any of the “Harkat” smart electronic services, the user shall have accepted the terms of use included in this agreement, and “Harkat” reserves the right to review the aforementioned terms at any time and announce any modification or change in the same, as well as to publish them on the recognized platforms, such as social media or other media channels.
The user shall be responsible for periodically checking the content on his account, including pictures and videos, and every written, visual or audio material, and “Harkat” Company shall not be responsible for the content or for moral or legal violations in the users’ accounts. In the event that the Company becomes aware of legal violations that are in conflict with the laws of the United Arab Emirates or recognized international laws, the Company shall have the right to suspend the user’s account, delete or modify the content and report any violations or breaches of the recognized laws of consumer rights, the organized crime law, the intellectual property law, trademark rights or tax rights or etc. Continuing to use smart electronic services in light of any amendments to the terms contained therein is considered an acceptance by the user of those amended terms and conditions.</p>

<strong>The Scope of Service and the Powers of “Harkat” to Modify the Same</strong><p>
“Harkat” Company is updating its policies, devices and software in line with its aspirations and directions and the aspiration of customers and beneficiaries of its services. Any electronic or smart services that are subsequently created will be subject to the terms of service in force at the time of their creation, unless otherwise agreed upon in a written agreement.
“Harkat” Company reserves the right at any time to amend, cancel or suspend any part of the services without prior notice. The user agrees that “Harkat” Company will not be liable towards him in any way because of any of the foregoing.
Controls of User Registration in the Company’s Smart Electronic Services and Access to and Use of the Same
The user is obligated to give all the information required to register correctly according to the registration form prepared for this purpose, and to update his data in the event of any change in the same. The Company reserves the right, at its discretion, to accept or reject his application for registration. From the date on which the registration is accepted, the user shall be completely responsible for his account of visual, readable, written or audible content and for all access to smart electronic services through his username and password, in addition he shall not disclose his username and password or share the use of the service or waive the same to any other party.
The user shall also be obligated to notify “Harkat” Company immediately in case he loses his account data or username, or in case of any unauthorized use of his account.
The user must verify the exit from his account after completing his activities and any damages that befall him as a result of failure to do so shall be on his full responsibility.
Also, user shall be responsible for any wrong expressions or incorrect or fraudulent information sent by him through electronic and smart media to our services.
The user shall comply with all applicable national or international laws and regulations, including those related to sending data, content or expressions. The user shall also verify that the subject, content, information conditions, e-mails, and the advertisements or other content belong to him do not contain, without limitation, hateful, vulgar, obscene, insulting, deceptive, or illegal written texts, as well as texts that violate the intellectual property rights or trademarks of any party whatsoever.</p>
<strong>Intellectual Property Rights</strong>
<p>“Harkat” Company alone owns all rights in relation to all services available on its smart electronic services and has the sole authority to dispose of them. The user is prohibited from using these contents or displaying them for other purposes or for any reason, other than by completely complying with the terms of service defined in this agreement, without written permission or an official approval in this regard. The user will be legally responsible for any violation or breach of any of the mentioned rights. In the event of any violation or breach by third parties of the mentioned rights or the user’s intellectual property rights related to the content and services or breach of the intellectual property rights of others, please inform us by e-mail: info@harakattransport.com
Controls for the Use of Smart Electronic Services
The user bears responsibility for the validity of the information that he enters through the Company’s smart platform and applications, as a user of the services performed through the same, and he acknowledges that the data and transactions he enters are dealt with without any additional review by the Company to verify it in other ways, and the Company does not bear any responsibility towards the user in the event of fining errors in the entered data.
The subscriber’s use of the username and password provided to him through this agreement is considered as his official signature on all smart electronic transactions and products that he officially submits and uses at “Harkat” Company, after fulfilling all the requirements and terms as well as providing information and details requested at the registration, in addition to attaching copies of documents and paying electronic fees for services through the Company’s website or smart application.
The user is prohibited from sending, by e-mail, or downloading, through the services of the “Harkat” Company, any computer viruses or others with the intention of destroying files, data, software, computer devices and systems, or communication equipment. It is also prohibited for him to send any content that he is not authorized to use, publish or reproduce, or that includes a violation or breach of the intellectual property rights of others.
User is not allowed to impersonate any person, misidentifying himself or using another user’s account without the permission of that user.
The user is also prohibited from copying, reproducing, publishing or selling all or some of the services for commercial purposes without written permission from the owner of the intellectual property or the property rights of the trade name. It is also prohibited for him to use the services in a manner that violates any applicable national or international laws or violates any internet protocols.
“Harkat” Company shall have the right to transfer or delete, according to its sole discretion, any content or information if it is considered objectionable by the Company for any reason, such as violating any condition of the current terms of service or any applicable law or instructions related to the same, or placed before users who has previously committed violations, without informing the Company in advance of their identities.
</p><strong>Technical Support</strong>
<p>“Harkat” Company is committed to providing the required technical support to ensure the availability of service and technical assistance during the official working hours of the Company, and this does not include the evening period.
</p><strong>Scope of Liability</strong>
<p>The user acknowledges that the data he records related to his name, password, residence, phone number, e-mail or any other data are all means of identification that determine his identity and that any transactions carried out using these means are considered to be issued by the user as his electronic signature and the Company considers any person uses the mentioned information is the user himself. The user is also responsible for all transactions that are carried out using his own identification information and is responsible for any change, loss, or transfer of any of the same to third parties until the Company is able to stop any violation of this information, based on a written notification from the user. The Company is also not responsible for disclosing the confidentiality of this information that may occur as a result of the user’s misuse or if this is done through electronic piracy operations.
Also, “Harkat” Company is not responsible for any damages arising from the following: loss of data, delay in operations for technical reasons, the content of third-party websites that are accessed through the smart electronic services provided by the Company, viruses that disrupt access to the service, incompatibility between the service and other services, programs or devices, the delay or failure of the user to initiate or complete the connection, misuse or inability to use the smart electronic services provided by the Company, the content, information, or any other materials presented on other websites which is accessed by links on the web that are available through “Harkat” Company electronic portal and through smart applications, and it will not be responsible for the use of the services of those other sites.
The user is obligated to install smart application updates that may be issued or published by the Company through the various means of publication, after the user installs the application for the purpose of developing or improving the service, and the Company is not responsible for any damages arising from the using of a previous version of the latest version of the application, that is available for download through the means of publication or through the official website of the Company, by the user.
Suspension or Termination of Service
“Harkat” Company may be forced to temporarily suspend the service for operational reasons such as maintenance of systems, development, updating of services, or other emergency reasons, without prior notification or specifying the period of suspension of service.
Also, any breach by the user of any condition of the current terms of service will lead to the closure of his account or to the immediate termination of all transactions related to him without prior notice as well as that such violations will be reported.
</p><strong>Divisibility of the Terms</strong><p>
Invalidation of an item or more of these conditions, due to its unlawfulness or unenforceability, shall not affect the validity of the rest of the other conditions and the same shall be effective.
Disputes, Arbitration and Governing Law
The user accepts the current terms of service, and future modifications on the same, and any dispute that arises from this service, whether related to interpretation or implementation, shall be settled through the competent court in accordance with the laws of the United Arab Emirates and is subject to the Company’s spatial jurisdiction.</p>
""";

String arabicTerms = """<strong>الغاية من الاحكام والشروط</strong><p>
نرحب بكم كمستخدمي لخدمات "حركات" الإلكترونية الذكية. وندعوك لقراءة هذه الشروط والأحكام بعناية. والتي نهدف منها تحديد المبادئ والالتزامات الضرورية للاستخدام للخدمات الإلكترونية الذكية المتاحة على المنصة الإلكترونية "حركات" من خلال بيان التزامات المستخدم وشروط الاستخدام.
تعريفات والمصطلحات في الشروط والاحكام</p>
<strong>يقصد في هذه الاتفاقية ما يلي:</strong><p>
الخدمات الإلكترونية الذكية: هي كل ما تقدمه شركة حركات من خدمات إلكترونية ذكية للمستخدمين المشتركين أو لغيرهم من المستخدمين في أي صورة من الصور الإلكترونية الذكية على سبيل المثال: تسجيل الاشتراك او إعلانات او طلب خدمة بأنواعها المختلفة واما بخصوص الدفع الإلكتروني الامن من خلال المنصة الذكية على تطبيق وموقع الشركة.
المستخدم : هو كل من يتاح له الاطلاع على كافة المحتويات والمواد المتوفرة في الموقع الرسمي لشركة "حركات" على التطبيقات الذكية وعلى جميع المنصات أو التعامل معها بأي صورة من الصور. سواء تم ذلك من خلال استخدام حساب الخدمة الخاص به ( اسم المستخدم وكلمة السر المسجلة ) وفي هذه الحالة يسمى مستخدم مشترك. أو أن يكون من المستخدمين الغير المشتركين.
المحتويات: يقصد بها جميع محتويات الخدمة من برمجيات وقواعد بيانات وما تضمنته من ملفات للبيانات أو النصوص المكتوبة أو الخرائط أو اسعار أو غير ذلك من المواد المصورة أو المكتوبة.
أقر بقراءة وفهم وقبول بجميع الشروط والاحكام الموجودة والمحدثة أو المعدلة.
بدخول المستخدم إلى أي من خدمات " حركات" الإلكترونية الذكية يكون قد قبل شروط الاستخدام المتضمنة في هذه الاتفاقية، وتحتفظ شركة " حركات" بالحق في مراجعة الشروط المذكورة في أي وقت والإعلان عن أي تعديل أو تغيير في تلك الشروط، ونشرها على القنوات المتعارف عليها من منصات التواصل الاجتماعي او القنوات الإعلامية الأخرة.
ويعتبر المستخدم مسؤولاً عن التأكد بشكل دوري على المحتوى الموجود على حسابه من صور و فيديوهات و كل مادة مكتوبة او مرئية او مسموعة وان شركة "حركات" غير مسؤوله عن المحتوى او عن المخالفات الأخلاقية او القانونية في حسابات المستخدمين و في حالت معرفة الشركة من وجود مخالفات قانونية تتعارض مع قوانين دولة الامارات العربية المتحدة او القوانين الدولية المتعارف عليها ان لشركة الحق في وقف حساب المستخدم او مسح او تعديل على المحتوى و البلاغ عن أي مخالفات او خروقات لقوانين المتعارف عليها من حقوق المستهلكين او قانون الجريمة المنظمة او قانون الحقوق الفكرية او حقوق العلامات التجارية او حقوق الضرائب او الخ...، ويعتبر الاستمرار في استخدام الخدمات الالكترونية الذكية في ضوء أي تعديلات تطرأ على الشروط الواردة فيه قبولا من طرف المستخدم بتلك الشروط والأحكام المعدلة.
</p>
نطاق الخدمة والصلاحيات "حركات" في تعديلها
تقوم شركة "حركات" على تحديث سياساتها وأجهزتها وبرمجياتها بما يتناسب مع تطلعاتها وتوجهاتها وتطلع العملاء والمستفيدين من خدماتها. وستخضع أي خدمات إلكترونية وأي خدمات ذكية يتم استحداثها لاحقا لشروط الخدمة المعمول بها وقت استحداثها، إلا إذا اتفق على غير ذلك بموجب اتفاق مكتوب.
تحتفظ شركة " حركات" بحقها في أي وقت بتعديل أو إلغاء أو تعليق وبدون إشعار مسبق أي جزء من الخدمات ويوافق المستخدم على أن شركة " حركات" لن تكون مسئولة تجاهه بأي شكل من الأشكال بسبب أي مما تقدم.
ضوابط تسجيل المستخدم في الخدمات الإلكترونية الذكية لشركة " حركات" ودخوله إليها واستخدامها.
يلتزم المستخدم بإعطاء جميع المعلومات المطلوبة للتسجيل بصورة صحيحة وفق نموذج التسجيل المعد لذلك. وبتحديث البيانات الخاصة به في حال حدوث أي تغيير يطرأ عليها. وتحتفظ الشركة بحقها وفقا لتقديرها بقبول أو رفض طلبه بالتسجيل. واعتبارا من تاريخ قبول تسجيله يكون مسئولا عن كل استعمالات على حسابه من محتوى مرئي او مقروء او مكتوب او مسموع وعن كل عمليات الدخول إلى الخدمات الالكترونية الذكية من خلال اسم المستخدم وكلمة المرور الخاصين به . ويلتزم بعدم الافصاح عنهما أو مشاركة استخدام الخدمة أو التنازل عنهما لأي طرف أخر .
كما يلتزم أيضاً بإشعار شركة " حركات" فوراً في حالة فقدانه لبيانات حسابه أو اسم المستخدم أو بأي استعمال غير مخول لحسابه.
ويجب أن يتحقق من الخروج من حسابه بعد الانتهاء من نشاطاته وأي أضرار تصيبه نتيجة لعدم الالتزام بذلك سيكون على مسئوليته الكاملة.
وبأنه سيكون مسؤول عن أي عبارات خاطئة أو معلومات غير صحيحة أو احتيالية مرسلة منه عبر الوسائط الإلكترونية والوسائط الذكية لخدماتنا.
ويلتزم بكافة القوانين والأنظمة الوطنية أو الدولية المطبقة، بما في ذلك تلك المتعلقة بإرسال البيانات أو محتوى أو عبارات، وبأن يتحقق من أن الموضوع والمحتوى وشروط المعلومات والبريد الإلكتروني والمحتوى المعلن أو غيره الخاصة به لا تحتوي ودون تحديد على كتابات مفعمة بالكراهية أو بذيئة أو فاحشة أو مهينة أو مخادعة أو غير قانونية. أو تنتهك حقوق الملكية الفكرية أو العلامات التجارية لأي جهة كانت.
حقوق الملكية الفكرية
شركة " حركات" وحدها المالكة لجميع الحقوق بالنسبة لكافة الخدمات المتاحة على خدماتها الإلكترونية الذكية وهي وحدها صاحبة التصرف فيها، ويحظر على المستخدم استعمال هذه المحتويات أو عرضها لغايات أخرى أو لأي سبب كان غير تلك المطابقة تماما لشروط الخدمة المعرفة بهذه الاتفاقية أو دون إذن كتابي أو تصريح رسمي بذلك. وبأنه سيكون مسؤولا قانونا عن أي مخالفة أو خرق لأي من هذه الحقوق، في حال حدوث أي مخالفة أو خرق من قبل الغير لهذه الحقوق أو لحقوق الملكية الفكرية الخاصة بالمستخدم المتعلقة بالمحتوى والخدمات يرجى ارسال  إلى شركة " حركات" أو خرق لحقوق الملكية الفكرية للغير يرجى إعلامنا عن طريق البريد الإلكتروني على info@harakattransport.com .

ضوابط استخدام الخدمات الإلكترونية الذكية
يتحمل المستخدم مسئولية صحة المعلومات التي يقوم بإدخالها عبر منصة وتطبيقات الذكية لشركة " حركات" باعتباره مستخدما للخدمات التي تؤدى من خلالها، و يقر بأن البيانات و المعاملات التي يدخلها يتم التعامل عليها بدون أية مراجعه إضافية من الشركة التأكد منها بطرق أخرى ولا تتحمل الشركة أية مسئولية تجاه المستخدم في حالة حدوث خطأ في البيانات التي يتم إدخالها .
ويعتبر استخدام المشترك في الخدمة لاسم المستخدم وكلمة السر المزودة له من خلال هذه الاتفاقية بمثابة التوقيع الرسمي له على جميع المعاملات الإلكترونية الذكية المنتوجات التي يقوم بتقديمها واستخدامها وعرضها رسمياً لدى شركة " حركات" بعد استيفاء المستخدم لجميع المتطلبات والشروط وتوفير المعلومات والبيانات المبينة عند التسجيل وإرفاق صور المستندات ودفع الرسوم إلكترونياً والمبينة لهذه الخدمات من خلال الموقع او التطبيق الذكي للشركة.
يحظر علي المستخدم أن يرسل عن طريق البريد الإلكتروني أو التحميل من خلال خدمات شركة " حركات" أي فيروسات برمجية أو غيرها بقصد إتلاف ملفات أو البيانات أو البرمجيات أو أجهزة وأنظمة الكمبيوتر أو معدات الاتصال. كما يحظر عليه أن يرسل أي محتوى غير مخول له استعماله، أو نشره وإعادة إنتاجه، أو يتضمن مخالفة أو خرقا لحقوق الملكية الفكرية للغير.
يحظر علي المستخدم انتحال شخصية أي شخص، أو تعريف نفسه بطريقة خاطئة أو استخدام حساب مستخدم آخر بغير تصريح من قبل ذلك المستخدم.
يحظر علي المستخدم نسخ أو إعادة إنتاج أو نشر أو بيع الخدمات كلها أو بعضها لغايات تجارية بدون إذن خطي من صاحب الملكية الفكرية او حقوق الملكية الاسم التجاري . كما يحظر عليه استخدام الخدمات بشكل يخرق أية قوانين وطنية أو دولية معمول بها أو يخالف أي بروتوكولات متعلقة بالإنترنت.
شركة " حركات " لها أن تنقل أو تمحو، وفقا لتقديرها وحدها أي محتوى، أو معلومات إذا اعتبر مثارا للاعتراض من قبلها لأي سبب كان، كأن يخالف أي شرط من شروط الخدمة الحالية أو أي قانون أو تعليمات مطبقة متعلقة به، أو موضوعة من قبل مستخدمين مخالفين سابقين دون إعلام الشركة مسبقا بهوياتهم.
الدعم الفني
تلتزم شركة " حركات" بتقديم الدعم الفني المطلوب لضمان توفر الخدمة والمساعدة الفنية خلال أوقات العمل الرسمي لشركة. ولا يشمل ذلك الفترة المسائية.
نطاق المسئولية
يقر المستخدم بأن ما يدونه من بيانات تتعلق باسمه أو كلمة السر أو موطنه أو رقم هاتفه أو بريده الإلكتروني أو أي بيانات أخرى تعتبر كلها وسائل تعريف تحدد هويته و أن أية عمليات يتم تنفيذها باستخدام هذه الوسائل تعتبر صادرة من المستخدم باعتبارها توقيع إلكتروني له وتعتبر الشركة أي شخص يستخدم هذه الوسائل هو المستخدم ، كما يكون المستخدم مسئولاً عن جميع العمليات التي يتم تنفيذها باستخدام وسائل التعريف الخاصة به ومسئولاً عن أي تغيير أو فقدان أو انتقال أي من تلك الوسائل إلى الغير لحين التوقيت الزمني الذى تتمكن فيه الشركة من إيقاف أي انتهاك لهذه البيانات بناء على إخطار كتابي من المستخدم كما إن الشركة غير مسئولة عن كشف سرية هذه البيانات التي قد تحدث نتيجة سوء استخدام المستخدم أو إذا تم ذلك عن طريق عمليات القرصنة الإلكترونية .
كما لا تكون شركة " حركات" مسؤولة عن أي أضرار تنشأ عن: فقدان في البيانات، أو تأخير في العمليات لأسباب تقنية، أو محتوى مواقع الغير التي يتم الوصول اليها من خلال الخدمات الإلكترونية الذكية التي تقدمها. أو عن الفيروسات التي تعطل الوصول إلى الخدمة أو عدم التوافق بين الخدمة وغيرها من الخدمات والبرامج والأجهزة. أو عن التأخير أو الفشل الراجع للمستخدم في بدء الاتصال أو إتمامه أو سوء الاستخدام أو عدم القدرة على استخدام ما تقدمه من خدمات إلكترونية الذكية أو عن المحتوى أو المعلومات أو أية مواد أخرى معروضة على المواقع الأخرى التي يتم الدخول عليها من خلال الربط على الشبكة (الويب) المتوفرة عن طريق بوابة شركة " حركات" الإلكترونية وعبر التطبيقات الذكية كما أنها لن تكون مسؤولة عن استخدامه لخدمات تلك المواقع الأخرى.
يلتزم المستخدم بتثبيت تحديثات التطبيقات الذكية التي قد يتم إصدارها أو نشرها من قبل الشركة من خلال وسائل نشر التطبيقات المختلفة بعد تثبيت المستخدم للتطبيق وذلك بغرض التطوير أو تحسين الخدمة، ولا تكون الشركة مسئولة عن أي أضرار تنشأ عن إستخدام المستخدم لنسخة سابقة لأخر إصدار للتطبيق متاح للتنزيل من خلال من خلال وسائل نشر التطبيقات المختلفة أو من خلال الموقع الرسمي لشركة " حركات".
إيقاف أو إنهاء الخدمة
قد تضطر شركة " حركات" الإيقاف المؤقت للخدمة لأسباب تشغيلية مثل صيانة الأنظمة أو التطوير أو تحديث الخدمات أو لأسباب طارئة أخرى دون إخطار مسبق أو تحديد مدة إيقاف الخدمة.
كما إن أي خرق من المستخدم لأي شرط من شروط الخدمة الحالية سيؤدي إلى إغلاق حسابه أو إلى الإنهاء الفوري لجميع العمليات المتعلقة به دون إشعار مسبق والإبلاغ عنه.
قابلية الشروط للتجزئة
لا يؤثر إلغاء بند أو اكثر من هذه الشروط – لعدم قانونيته أو قابليته للتنفيذ – على سريان باقي الشروط الأخرى باعتبارها نافذة المفعول ومنتجة لأثرها
المنازعات والتحكيم والقانون الواجب تطبيقه
 يقبل المستخدم بشروط الخدمة الحالية –وما قد يطرأ عليها من تعديلات مستقبلية- وأي نزاع ينشأ عن هذه الخدمة سواء تعلق بالتفسير أو التنفيذ يفض عن طريق المحكمة المختصة وفقا لقوانين دولة الامارات العربية المتحدة ويخضع للاختصاص المكاني لشركة.
""";
